name: Check for Hardcoded K Numbers

on: [push]

jobs:
  check-hardcoded-k:
    runs-on: windows-latest  # Use Windows environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for hardcoded K numbers
        shell: pwsh  # Explicitly use PowerShell
        run: |
          # Scan all Python files for a "K" number (e.g., K1234567)
          $forbidden_k = (Select-String -Path *.py -Pattern "K[0-9]{7}" -AllMatches)

          # If a K number is found, print an error and fail the workflow
          if ($forbidden_k) {
            Write-Host "The following hardcoded K numbers were found:"
            $forbidden_k | ForEach-Object { Write-Host $_.Line }
            exit 1  # Fail the workflow if a match is found
          } else {
            Write-Host "No hardcoded K numbers found."
          }
