name: R workflow - Check Addition Functionality

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - '**/tutorials.md'


jobs:
    check-versions:
          runs-on: windows-latest
          # checkout the repository
          steps:
             - name: Checkout code
               uses: actions/checkout@v4

          # Set up R enviroment
             - name: Set up R
               uses: r-lib/actions/setup-r@v2
               with:
                   r-version: 'latest'
          # Install ggplot2
             - name: Install ggplot2
               run: |
                   Rscript -e 'install.packages("ggplot2")'

      # checks if the function works
             - name: Run addFunction in R
               run: |
                 Rscript -e 'source("RAdditionFunction.r"); addFunction(10,10)' # Prints R version
