name: check for dependencies in R 

on: [push]

jobs:
    check-versions:
          runs-on: windows-latest
          # checkout the repository
          steps:
             - name: Checkout code
               uses: actions/checkout@v4

          # Set up R enviroment
             - name: Set up R
               uses: r-lib/actions/setup-r@v2
               with:
                   r-version: 'latest'
          # Install ggplot2
             - name: Install ggplot2
               run: |
                   Rscript -e if(!require(ggplot2)) install.packages("ggplot2")

      # checks the versions of both R and ggplot2
             - name: Check R and ggplot2 versions
               run: |
                 Rscript -e 'cat("R version:\n"); print(R.version)' # Prints R version
                 Rscript -e 'cat("\nggplot2 Version:\n"); packageVersion("ggplot2")'# Prints ggplot version

               


              
    


         
