name: R Workflow -  Style Check

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
jobs:
  style-check:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Step 3: Install styler
      - name: Install styler
        run: |
          Rscript -e 'install.packages("styler")'

      # Step 4: Check code style with styler
      - name: Run styler to check formatting
        run: |
          Rscript -e 'styler::style_dir(".", strict = TRUE)'
