name: Test String Function 

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup Python
      uses: actions/checkout@v4
      with:
        python-version: '3.9'
    - name: Running String Function
      run: |
        python StringFunction.py
