name: Check if any script contains forbidden contents(ward names) from .txt

on:
  push:
    paths:
      - '**.py'
      - '**.r'
      
  

jobs:
  check_forbidden_content:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if any script contains forbidden content
        shell: pwsh  # Ensure PowerShell is used
        run: |
          # Get the content from the forbidden.txt file
          $wardNames = Get-Content -Path "wardnames.txt"

          # Find all scripts except README.md
          $scripts = Get-ChildItem -Recurse -Include *.py, *.r -Exclude README.md, tutorials.md 

          foreach ($script in $scripts) {
              # Check each script for each ward name using Select-String
              foreach ($wardName in $wardNames) {
                  $match = Select-String -Path $script.FullName -Pattern $wardName
                  if ($match) {
                      Write-Host "Hardcoded ward name found: $wardName in $($script.FullName)"
                      exit 1  # Fail the workflow if a match is found
                  }
              }
          }
 
          Write-Host "No hardcoded ward names found."
         
        
